import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";
import os from "os";
import { createLogger } from "../utils/index.js";
import type { Gallery } from "../types/index.js";

const log = createLogger("pdf");

/** Format tags into a compact string */
function formatTags(tags: string[], maxLen = 80): string {
  const joined = tags.join(", ");
  if (joined.length <= maxLen) return joined;
  return joined.slice(0, maxLen - 3) + "...";
}

/** Generate a compact PDF of galleries list */
export async function generatePdf(
  galleries: Gallery[],
  username: string,
  filterInfo?: string
): Promise<string> {
  const tmpDir = path.join(os.tmpdir(), "nsaver-pdfs");
  if (!fs.existsSync(tmpDir)) {
    fs.mkdirSync(tmpDir, { recursive: true });
  }
  const filePath = path.join(
    tmpDir,
    `nsaver_${username}_${Date.now()}.pdf`
  );

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margin: 40,
        compress: true, // Keep PDF size small
        info: {
          Title: `nsaver - Favorites for ${username}`,
          Author: "nsaver bot",
          Subject: "nhentai Favorites Export",
        },
      });

      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      // Header
      doc
        .fontSize(18)
        .font("Helvetica-Bold")
        .text("nsaver - Favorites Export", { align: "center" });

      doc
        .fontSize(10)
        .font("Helvetica")
        .text(`User: ${username}`, { align: "center" });

      doc.text(
        `Generated: ${new Date().toISOString().split("T")[0]}`,
        { align: "center" }
      );

      doc.text(`Total: ${galleries.length} galleries`, {
        align: "center",
      });

      if (filterInfo) {
        doc
          .fontSize(9)
          .fillColor("#666666")
          .text(`Filter: ${filterInfo}`, { align: "center" });
      }

      doc.moveDown(1);
      doc
        .strokeColor("#cccccc")
        .lineWidth(0.5)
        .moveTo(40, doc.y)
        .lineTo(555, doc.y)
        .stroke();
      doc.moveDown(0.5);

      // Gallery list
      for (let i = 0; i < galleries.length; i++) {
        const g = galleries[i];

        // Check if we need a new page
        if (doc.y > 720) {
          doc.addPage();
        }

        // Gallery number + ID
        doc
          .fontSize(10)
          .font("Helvetica-Bold")
          .fillColor("#000000")
          .text(`${i + 1}. [${g.id}] ${g.title}`, {
            width: 515,
            lineGap: 1,
          });

        // Metadata line
        const meta: string[] = [];
        if (g.language) meta.push(`Lang: ${g.language}`);
        if (g.category) meta.push(`Cat: ${g.category}`);
        if (g.pages > 0) meta.push(`${g.pages}p`);
        meta.push(`nhentai.net/g/${g.id}`);

        doc
          .fontSize(8)
          .font("Helvetica")
          .fillColor("#444444")
          .text(meta.join(" | "), { width: 515 });

        // Tags
        if (g.tags.length > 0) {
          doc
            .fontSize(7)
            .fillColor("#888888")
            .text(`Tags: ${formatTags(g.tags, 100)}`, { width: 515 });
        }

        doc.moveDown(0.3);
      }

      // Footer
      doc
        .fontSize(7)
        .fillColor("#aaaaaa")
        .text(
          "\n---\nGenerated by nsaver bot",
          { align: "center" }
        );

      doc.end();

      stream.on("finish", () => {
        const stats = fs.statSync(filePath);
        log.info(
          `PDF generated: ${filePath} (${(stats.size / 1024).toFixed(1)} KB)`
        );
        resolve(filePath);
      });

      stream.on("error", reject);
    } catch (err) {
      reject(err);
    }
  });
}

/** Clean up a temporary PDF file */
export function cleanupPdf(filePath: string): void {
  try {
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
      log.debug(`Cleaned up: ${filePath}`);
    }
  } catch (err) {
    log.warn(`Failed to clean up ${filePath}`);
  }
}
